/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `maven-publish`
    kotlin("jvm") version "1.4.32"
}

group = project.property("group").toString()
version = project.property("version").toString()

repositories {
    google()
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }

    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.32")
    }
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    testImplementation(kotlin("test"))
    implementation("com.github.glwithu06:semver.kt:1.0.1")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
        freeCompilerArgs = listOf(
            "-Xopt-in=kotlin.Experimental",
            "-Xopt-in=kotlin.ExperimentalStdlibApi"
        )
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

val sourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
    from(sourceSets.main.get().allSource)
}

artifacts {
    add("archives", sourcesJar)
}

val publicationName = "DependencyValidation"
publishing {
    publications {
        create<MavenPublication>(publicationName) {
            from(components["java"])
            artifact(sourcesJar.get())

            groupId = project.property("group").toString()
            version = project.property("version").toString()
            artifactId = project.property("artifact").toString()

            pom {
                name.set("App Rail")
                url.set("https://app-rail.io")
                licenses {
                    license {
                        name.set("Apache 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0.html")
                        distribution.set("repo")
                    }
                }
                developers {
                    developer {
                        id.set("futureworkshops")
                        name.set("Future Workshops")
                        email.set("info@futureworkshops.com")
                    }
                }
            }
        }
    }
}
