name: Deploy

on:
  release:
    types: [created]

jobs:
  publish:
    environment: main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Extract Tag
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/*/}
      - name: Publish Package
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_VERSION: ${{ steps.tag.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew clean publish "-Pgpr.user=${GITHUB_ACTOR}" "-Pgpr.key=${GITHUB_TOKEN}" "-Pversion=${BUILD_VERSION}"